"""initial schema

Revision ID: 3b5d930889a2
Revises: 
Create Date: 2026-09-08 15:26:19.932873
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '3b5d930889a2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('card_type', sa.Enum('prepaid_forex', 'multi_currency_forex', 'single_currency_forex', 'travel_debit', name='cardtype', native_enum=False, length=40), nullable=False),
    sa.Column('network', sa.Enum('visa', 'mastercard', 'rupay', 'multiple', 'unknown', name='cardnetwork', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('affiliate_provider', sa.String(length=120), nullable=True),
    sa.Column('affiliate_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards')),
    sa.UniqueConstraint('slug', name='uq_cards_slug')
    )
    op.create_index('ix_cards_is_active', 'cards', ['is_active'], unique=False)
    op.create_index('ix_cards_provider', 'cards', ['provider'], unique=False)
    op.create_table('fx_rate_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rate_cache')),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'provider', name='uq_fx_rate_cache_base_currency')
    )
    op.create_index('ix_fx_rate_cache_retrieved_at', 'fx_rate_cache', ['retrieved_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole', native_enum=False, length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_session_id_created_at', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recommended_card_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_card_id'], ['cards.id'], name=op.f('fk_recommendations_recommended_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_recommendations_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_session_id_created_at', 'recommendations', ['session_id', 'created_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('official_product_page', 'official_fee_schedule', 'official_terms', 'official_faq', 'secondary_source', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_sources_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_card_id', 'sources', ['card_id'], unique=False)
    op.create_table('tool_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('started', 'success', 'error', name='toolstatus', native_enum=False, length=40), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_tool_events_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_events'))
    )
    op.create_index('ix_tool_events_session_id_started_at', 'tool_events', ['session_id', 'started_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_user_profiles_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('session_id', name=op.f('uq_user_profiles_session_id'))
    )
    op.create_table('verification_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='verificationrunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('triggered_by', sa.String(length=60), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('changes_proposed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_verification_runs_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    op.create_table('card_benefits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('benefit_type', sa.Enum('cashback', 'discount', 'lounge_access', 'insurance', 'travel', 'emergency_assistance', 'fraud_protection', 'card_controls', 'transaction_alerts', 'emergency_replacement', 'online_management', 'online_application', 'online_reload', 'other', name='benefittype', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_benefits_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_card_benefits_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_benefits'))
    )
    op.create_index('ix_card_benefits_card_id', 'card_benefits', ['card_id'], unique=False)
    op.create_table('card_currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('direct_wallet', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(currency_code) = 3', name=op.f('ck_card_currencies_currency_code_iso4217')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_currencies_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_card_currencies_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_currencies')),
    sa.UniqueConstraint('card_id', 'currency_code', name='uq_card_currencies_card_id')
    )
    op.create_table('card_eligibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.Enum('min_age', 'residency', 'student_only', 'existing_relationship', 'documentation', 'purpose', 'other', name='eligibilitycriterion', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_eligibility_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_card_eligibility_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_eligibility'))
    )
    op.create_index('ix_card_eligibility_card_id', 'card_eligibility', ['card_id'], unique=False)
    op.create_table('card_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.Enum('issuance', 'reload', 'atm_withdrawal', 'cross_currency', 'replacement', 'encashment', 'inactivity', 'balance_enquiry', 'transaction', 'other', name='feetype', native_enum=False, length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_unknown', sa.Boolean(), nullable=False),
    sa.Column('is_waived', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount IS NOT NULL OR percentage IS NOT NULL OR is_unknown = true', name=op.f('ck_card_fees_fee_has_value_or_is_explicitly_unknown')),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_card_fees_amount_non_negative')),
    sa.CheckConstraint('max_amount IS NULL OR max_amount >= 0', name=op.f('ck_card_fees_max_amount_non_negative')),
    sa.CheckConstraint('min_amount IS NULL OR min_amount >= 0', name=op.f('ck_card_fees_min_amount_non_negative')),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name=op.f('ck_card_fees_percentage_in_range')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_fees_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_card_fees_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_fees'))
    )
    op.create_index('ix_card_fees_card_id_fee_type', 'card_fees', ['card_id', 'fee_type'], unique=False)
    op.create_table('card_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('limit_type', sa.Enum('daily_atm', 'daily_spend', 'monthly_reload', 'annual_reload', 'wallet_limit', 'atm_per_day_count', name='limittype', native_enum=False, length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_card_limits_amount_non_negative')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_limits_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_card_limits_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_limits'))
    )
    op.create_index('ix_card_limits_card_id', 'card_limits', ['card_id'], unique=False)
    op.create_table('verification_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_verification_changes_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], name=op.f('fk_verification_changes_run_id_verification_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_verification_changes_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_changes'))
    )
    op.create_index('ix_verification_changes_status', 'verification_changes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_changes_status', table_name='verification_changes')
    op.drop_table('verification_changes')
    op.drop_index('ix_card_limits_card_id', table_name='card_limits')
    op.drop_table('card_limits')
    op.drop_index('ix_card_fees_card_id_fee_type', table_name='card_fees')
    op.drop_table('card_fees')
    op.drop_index('ix_card_eligibility_card_id', table_name='card_eligibility')
    op.drop_table('card_eligibility')
    op.drop_table('card_currencies')
    op.drop_index('ix_card_benefits_card_id', table_name='card_benefits')
    op.drop_table('card_benefits')
    op.drop_table('verification_runs')
    op.drop_table('user_profiles')
    op.drop_index('ix_tool_events_session_id_started_at', table_name='tool_events')
    op.drop_table('tool_events')
    op.drop_index('ix_sources_card_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_recommendations_session_id_created_at', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_messages_session_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_index('ix_fx_rate_cache_retrieved_at', table_name='fx_rate_cache')
    op.drop_table('fx_rate_cache')
    op.drop_index('ix_cards_provider', table_name='cards')
    op.drop_index('ix_cards_is_active', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
